# Generated by Django 2.1.8 on 2019-07-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='pptfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
