# Generated by Django 2.1.8 on 2019-07-14 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_market_pptfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='pptfile',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='market',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
