# Generated by Django 2.1.8 on 2019-07-14 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_market_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='slug',
        ),
    ]
