# Generated by Django 2.1.8 on 2019-07-16 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_market_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
