# Generated by Django 2.1.8 on 2019-07-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_auto_20190716_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='summary',
        ),
    ]
