# Generated by Django 2.1.8 on 2019-07-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_remove_market_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='image',
        ),
    ]
