# Generated by Django 2.1.8 on 2019-07-16 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0009_remove_market_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='market',
            name='summary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
