# Generated by Django 2.1.8 on 2019-07-16 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0010_auto_20190716_1925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='image',
        ),
        migrations.RemoveField(
            model_name='market',
            name='summary',
        ),
    ]
