# Generated by Django 2.1.8 on 2019-08-06 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0015_auto_20190806_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='market',
            name='scrap_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
