# Generated by Django 2.1.8 on 2019-08-06 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0016_market_scrap_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='scrap_count',
        ),
    ]
