# Generated by Django 2.1.8 on 2019-08-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeytip', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='notion',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
