# Generated by Django 2.1.8 on 2019-08-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeytip', '0003_hitcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='tip',
            name='group',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
