# Generated by Django 2.1.8 on 2019-08-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeytip', '0004_tip_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tip',
            name='group',
            field=models.CharField(choices=[('GU', '귀차니즘'), ('SI', '시간절약'), ('GA', '간지폭발')], max_length=10),
        ),
    ]
