# Generated by Django 2.1.8 on 2019-08-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('honeytip', '0006_auto_20190809_2102'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tip',
            name='body',
        ),
        migrations.AlterField(
            model_name='tip',
            name='group',
            field=models.CharField(choices=[('귀차니즘', '귀차니즘'), ('시간절약', '시간절약'), ('폭풍간지', '폭풍간지')], max_length=10),
        ),
    ]
