# Generated by Django 2.1.8 on 2019-08-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('msg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msg',
            name='group',
            field=models.CharField(choices=[('color', 'color'), ('img', 'img'), ('template', 'template'), ('font', 'font')], max_length=10, null=True),
        ),
    ]
